### ISSUE TITLE
Make It Customizable

### ISSUE THREAD

**Issue by epipi237** [gastonche/expression-viewer#1]
I think this package is great and can be used much for expression visualization for genes or proteins. I think right now it can be enhanced by making it more customizable by the end user

**Comment by gastonche** [comment]
okay epipi237 you could go ahead and see what you could to customize it. while i also try to make enhancements. But note that it is far from being perfect or complete

**Comment by epipi237** [comment]
hey gastonche.have you checked the work done?.i think now the package is more customizable by the user just check the functionality and get to me thanks.

**Comment by gastonche** [comment]
Okay epipi237, i saw your pull request and have gone through what you did. They are all good so i have merged the changes with mine. Thanks for contributing to expression-viewer
